// app/layout.tsx
import "./globals.css";
import { ReactNode } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  modal, // ← parallel route `@modal` から自動で渡される
}: {
  children: ReactNode;
  modal: ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="bg-white text-gray-900 font-sans">
        <Header />
        <main className="max-w-6xl mx-auto px-4 py-8 min-h-screen">
          {children}
          {modal}
        </main>
        <Footer />
      </body>
    </html>
  );
}
